## 设置项目端口号
server:
  address: localhost
  port: 8080
  servlet:
    context-path: /
    encoding:
      force: true
      charset: UTF-8
      enabled: true


## 设置项目启用的配置文件。dev为生产环境，test为测试环境。
spring:
  profiles:
    active: test


## 不同环境中数据源的配置。【测试环境-test】、【生产环境-dev】
---
## 测试环境
spring:
  profiles: test
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hive?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      # 初始化连接数
      initial-size: 1
      # 最小闲置数
      min-idle: 3
      # 最大活跃数
      max-active: 4
      # 获取连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

---
## 生产环境
spring:
  profiles: dev
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hive?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      # 初始化连接数
      initial-size: 1
      # 最小闲置数
      min-idle: 3
      # 最大活跃数
      max-active: 4
      # 获取连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
---

## Mybatis的配置，使用Mybatis-Plus中间件
mybatis-plus:
  # 启动时是否检查MyBatis对应的XML文件是否存在
  check-config-location: true
  type-aliases-package: com.xinyuow.frame.model.**
  mapper-locations: classpath:/mapper/*Mapper.xml
#  type-handlers-package: com.xinyuow.frame.common.mybatis
  global-config:
    db-config:
      # 主键ID生成策略，当前为用户手动输入ID
      id-type: input
      # 逻辑已删除值(默认为1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为0)
      logic-not-delete-value: 0
  configuration:
    # 设置Select语句的延迟加载是否开启
    lazy-loading-enabled: true
    # 为true时，相关级联查询均会马上执行。为false时，相关级联查询的属性被使用时才会执行查询。
    aggressive-lazy-loading: false
    # 是否开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 是否在日志中输出SQL语句，在开发或测试的时候可以使用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
